//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHI.Urban.Delineation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHI.Urban.Delineation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Surface Flow.
        /// </summary>
        internal static string Caption_FlowTracingTool {
            get {
                return ResourceManager.GetString("Caption_FlowTracingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry.
        /// </summary>
        internal static string Caption_InvalidEntry {
            get {
                return ResourceManager.GetString("Caption_InvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Caption_Notice {
            get {
                return ResourceManager.GetString("Caption_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Catchment Delineation.
        /// </summary>
        internal static string Caption_SetupCommand {
            get {
                return ResourceManager.GetString("Caption_SetupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delineate Urban Catchments.
        /// </summary>
        internal static string Caption_UrbanDelineationCommand {
            get {
                return ResourceManager.GetString("Caption_UrbanDelineationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zingers.
        /// </summary>
        internal static string Caption_ZingerCommand {
            get {
                return ResourceManager.GetString("Caption_ZingerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHI Urban Delineation.
        /// </summary>
        internal static string Category_UrbanDelineation {
            get {
                return ResourceManager.GetString("Category_UrbanDelineation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DHI {
            get {
                object obj = ResourceManager.GetObject("DHI", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flow direction grid has not been setup. Please use the Setup form to select or generate a flow direction grid..
        /// </summary>
        internal static string Error_NoFlowDirection {
            get {
                return ResourceManager.GetString("Error_NoFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FlowTracingCursor {
            get {
                object obj = ResourceManager.GetObject("FlowTracingCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlowTracingIcon {
            get {
                object obj = ResourceManager.GetObject("FlowTracingIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a graphic to the map showing the surface flow path from the point clicked downstream to an inlet or the edge of the DEM..
        /// </summary>
        internal static string Message_FlowTracingTool {
            get {
                return ResourceManager.GetString("Message_FlowTracingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog to specify and prepare data for urban catchment delineation..
        /// </summary>
        internal static string Message_SetupCommand {
            get {
                return ResourceManager.GetString("Message_SetupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog for delineating urban catchments associated with a pipe network..
        /// </summary>
        internal static string Message_UrbanDelineationCommand {
            get {
                return ResourceManager.GetString("Message_UrbanDelineationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects geometries in two different layers with arrows (&quot;zingers&quot;) based on selected id fields..
        /// </summary>
        internal static string Message_ZingerCommand {
            get {
                return ResourceManager.GetString("Message_ZingerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no selection).
        /// </summary>
        internal static string No_Selection {
            get {
                return ResourceManager.GetString("No_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        internal static string Optional_Field {
            get {
                return ResourceManager.GetString("Optional_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SetupIcon {
            get {
                object obj = ResourceManager.GetObject("SetupIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UrbanDelineationIcon {
            get {
                object obj = ResourceManager.GetObject("UrbanDelineationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Selected Network Nodes&gt;.
        /// </summary>
        internal static string Use_Selected_Nodes {
            get {
                return ResourceManager.GetString("Use_Selected_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZingerIcon {
            get {
                object obj = ResourceManager.GetObject("ZingerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
